// ============================================================================
// Source: app/manifest.ts
// Version: 1.0.0 — 2026-08-24
// Why: PWA manifest, generated by Next so it stays in step with the metadata
//      rather than living as a hand-maintained static file.
// Env / Identity: Public.
// ============================================================================
import type { MetadataRoute } from "next";
import { brand } from "@goplaza/core";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "GOPLAZA — دایرکتوری کسب‌وکارهای ایرانیان کانادا",
    short_name: "GOPLAZA",
    description: `${brand.tagline.fa} دایرکتوری کسب‌وکارهای ایرانی در کانادا.`,
    start_url: "/",
    display: "standalone",
    background_color: "#F6F1E8",
    theme_color: "#7A1831",
    lang: "fa",
    dir: "rtl",
    icons: [
      { src: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      {
        src: "/android-chrome-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
